---

- name: Create a GlucoseTracker production server
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars:
    - setup_git_repo: yes
    - setup_cron_jobs: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/{{ env }}.yml

  roles:
    - base
    - certbot
#    - db
    - web
    - nginx
